name: metrics
on:
  schedule:
    - cron: "0 18 * * *"
  push: {branches: ["master", "main"]}
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:

          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: metrics

          template: classic
          base: header, activity, community, repositories
          repositories_affiliations: ''
          config_timezone: Europe/London

          plugin_achievements: yes
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C

          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_visibility: all

          plugin_followup: yes
          plugin_followup_sections: repositories

          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_colors: github
          plugin_languages_limit: 10
          plugin_languages_threshold: 0%

          plugin_lines: yes

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_notable: yes
          plugin_projects: yes
          plugin_projects_limit: 4
