# usages: https://github.com/search?o=desc&q=lowlighter%2Fmetrics+path%3A.github%2Fworkflows+language%3AYAML&s=&type=Code
# action: https://github.com/lowlighter/metrics
# example: https://github.com/afrizaloky/afrizaloky/blob/70044b44fff97784144dacc4e80f7b08328c701c/.github/workflows/main.yml
# example2: https://github.com/Variiuz/variiuz/blob/e406a1f4c7389d9a0383b8839702e78ce81ab9f4/.github/workflows/stuff.yml
name: metrics
on:
  schedule:
    - cron: "0 18 * * *"
  push: {branches: ["master", "main"]}
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: 📰 Activity plugin
        uses: lowlighter/metrics@master
        if: always()
        with:
          filename: metrics.plugin.activity.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: metrics
          plugin_activity: yes
          plugin_activity_limit: 7
          plugin_activity_days: 0
          plugin_activity_filter: issue, pr, release, fork, star
          config_padding: 7%, 20%

      - name: 📅 Isocalendar plugin (full year)
        uses: lowlighter/metrics@master
        if: always()
        with:
          filename: metrics.plugin.isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: metrics
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

      - name: 🈷️ Languages plugin (detailed)
        uses: lowlighter/metrics@master
        if: always()
        with:
          filename: metrics.plugin.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: metrics
          plugin_languages: yes

      # full
      - uses: lowlighter/metrics@latest
        if: always()
        with:

          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: metrics

          template: classic
          base: header, activity, community, repositories
          repositories_affiliations: owner, collaborator, organization_member
          config_timezone: Europe/London

          plugin_achievements: yes
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_achievements_limit: 0

          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_visibility: all

          plugin_followup: yes
          plugin_followup_sections: repositories

          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_colors: github
          plugin_languages_limit: 10
          plugin_languages_threshold: 2%

          plugin_lines: yes

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_notable: yes
          plugin_projects: yes
          plugin_projects_limit: 4

          plugin_habits: yes
          plugin_habits_from: 200       # Use 200 events to compute habits
          plugin_habits_days: 14        # Keep only events from last 14 days
          plugin_habits_facts: yes      # Display facts section
          plugin_habits_charts: yes     # Display charts section
